config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get "/", to: "pages#home"
  resources :books
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @author = current_author
    #first way
    # @book = @author.books.build(book_params)
    # @book.save

    #second way
    @book = @author.books.create(book_params)
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/index.html.erb
<h1>These are the authors!</h1>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author %></li>
  <% end %>
</ul>

<% if author_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_author_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_author_session_path)  %>  
  </li>
<% end %>

app/views/authors/show.html.erb
<h1>These are <%= @author.name %>'s Books!</h1>

<ul>
  <% @author.books.each do |book| %>
    <li><%= book.title %></li>
  <% end %>
</ul>

<p>Be Carefull!</p>
<%= form_tag(@author, method: "delete") do %>
  <%= submit_tag("Delete Autor!") %>
<% end %>

app/views/books/index.html.erb
<h1>The Books!</h1>
<ul>
  <% @books.each do |book| %>
    <li>"<%= book.title %>" by <%= book.author.name %></li>
  <% end %>
</ul>

<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<h1>Create New Book!</h1>
<%= form_for @book do |f| %>
  <%= f.text_field :title, placeholder: "Create a Book!" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nov9</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to The Books App!</h1>

<%= link_to "Check out the Authors", authors_path %>
<br>
<br>
<%= link_to "Check out the Books", books_path %>